sites:
  - name: "CrazyGames"
    sitemap_urls:
      - "https://www.crazygames.com/en/sitemap"
    active: true
  - name: "GameDistribution"
    sitemap_urls:
      - "https://gamedistribution.com/sitemap-games-1.xml"
    active: true
  - name: "MiniPlay"
    sitemap_urls:
      - "https://www.miniplay.com/sitemap-games-3.xml"
    active: true
  - name: "Poki"
    sitemap_urls:
      - "https://poki.com/en/sitemaps/games.xml"
    active: true
  - name: "SpotleGame"
    sitemap_urls:
      - "https://spotlegame.com/sitemap.xml"
    active: true
  - name: "Lagged"
    sitemap_urls:
      - "https://lagged.com/sitemap.xml"
    active: true

feishu:
  webhook_url: "https://open.feishu.cn/open-apis/bot/v2/hook/c84594b9-e8dd-4828-a24d-cb1175f41f3a"
  secret: "YOUR_SECRET"

storage:
  retention_days: 7
  data_dir: "./data"
